services:

  core-webapi:
    build:
      context: .
      dockerfile: ./src/Job.WebApi/Dockerfile
    image: mottu/core-webapi:latest
    container_name: core-webapi
    user: "0:0"
    ports:
      - '5001:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: 'Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=job;'
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: '5672'
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      Cors__AllowedOrigins__0: http://localhost:4200
    volumes:
      - uploads-data:/app/uploads
    networks:
        - core-network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
        - core-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
  rabbitmq-data:
  uploads-data:

networks:
  core-network:
    driver: bridge
