services:

  core-webapi:
    build:
      context: .
      dockerfile: ./src/Job.WebApi/Dockerfile
    user: app
    container_name: core-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5001:8080'
    networks:
        - core-network
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job
    restart: unless-stopped
    networks:
        - core-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  uploads-data:

networks:
  core-network:
    driver: bridge
